### ISSUE TITLE
Not Working with Angular cli 9 

### ISSUE THREAD

**Issue by kaariwedoms** [yildiraymeric/ngx-connection-service#18]
I have followed all the instructions steps given for installation, still i am not able to detect application state 

In my project , I am using 
![image](https://user-images.githubusercontent.com/8941091/122158174-cb34ab00-ce89-11eb-93a3-364a44562faf.png)

Please give/suggest me a workaround

**Comment by geniltodallo** [comment]
Not working with Angular CLI 12.0.5 too on Windows. MacOSx works.

Angular CLI: 12.0.5
Node: 14.17.0
Package Manager: npm 6.14.13
OS: win32 ia32

Angular: 12.0.5
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, material
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.5
@angular-devkit/build-angular   12.0.5
@angular-devkit/core            12.0.5
@angular-devkit/schematics      12.0.5
@angular/flex-layout            12.0.0-beta.34
@schematics/angular             12.0.5
rxjs                            6.5.5
typescript                      4.2.4

**Comment by yildiraymeric** [comment]
Following versions are added to npm registry, please use the one that suits you project;

| *ngx-connection-service version* | *Angular version* |
|----------------------------------|-------------------|
| 7.0.x                            | 7.2.16            |
| 8.0.x                            | 8.2.14            |
| 9.0.x                            | 9.1.13            |
| 10.0.x                           | 10.2.5            |
| 11.0.x                           | 11.2.14           |
| 12.0.x                           | 12.2.17           |
| 13.0.x                           | 13.4.0            |
| 14.0.x                           | 14.3.0            |
| 15.0.x                           | 15.2.9            |
| 16.0.x                           | 16.1.8            |
