### ISSUE TITLE
CommonJS or AMD dependencies can cause optimization bailouts.

### ISSUE THREAD

**Issue by Jun711** [yildiraymeric/ngx-connection-service#6]
In Angular 9, 10, there is warning about use of CommonJS.

```
WARNING in /Users/Projects/projectA/node_modules/ngx-connection-service/__ivy_ngcc__/fesm2015/ngx-connection-service.js depends on 'lodash'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

From https://angular.io/guide/build#configuring-commonjs-dependencies
```
It is recommended that you avoid depending on CommonJS modules in your Angular applications. Depending on CommonJS modules can prevent bundlers and minifiers from optimizing your application, which results in larger bundle sizes. Instead, it is recommended that you use ECMAScript modules in your entire application.
```

In short, to solve this, don't use lodash or only use lodash when they use ECMAScript to write lodash.

**Comment by yildiraymeric** [comment]
"lodash" dependency will be removed in next releases.

**Comment by yildiraymeric** [comment]
"lodash" dependency is removed in following versions;

| *ngx-connection-service version* |
|----------------------------------|
| 7.0.7                            |
| 8.0.2                            |
| 9.0.1                            |
| 10.0.1                           |
| 11.0.1                           |
| 12.0.1                           |
| 13.0.1                           |
| 14.0.1                           |
| 15.0.1                           |
| 16.0.1                           |
